# 1. build-assets
# 2. build api container
# 3. push container to GCR
# 4. deploy to Cloud Run
# 5. deploy assets to Firebase Hosting

steps:
  - name: node:12.14.1
    entrypoint: npm
    args:
      - install
  # Ref. https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials?hl=ja#using_the_encrypted_variable_in_build_requests
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - "gcloud secrets versions access latest --secret=api_url --format='get(payload.data)' | tr '_-' '/+' | base64 -d > api_url.txt"
  - name: node:12.14.1
    entrypoint: bash
    args:
      - "-c"
      - "API_URL=$(cat api_url.txt) npm run build:production"
  - name: gcr.io/kaniko-project/executor:v0.23.0
    args:
      - --context=api/
      - --dockerfile=Dockerfile
      - --target=default
      - --destination=gcr.io/$PROJECT_ID/torii-api:$COMMIT_SHA
      - --build-arg=COMMIT_SHA=$COMMIT_SHA
      - --cache=true
      # Two weeks
      - --cache-ttl=336h
  - name: gcr.io/kaniko-project/executor:v0.23.0
    args:
      - --context=api/
      - --dockerfile=Dockerfile
      - --target=default
      - --destination=gcr.io/$PROJECT_ID/torii-api:latest
      - --cache=true
      # Two weeks
      - --cache-ttl=336h
  # # Deploy an image from Container Registry to Cloud Run
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args:
  #     - 'run'
  #     - 'deploy'
  #     - '[SERVICE_NAME]'
  #     - '--image'
  #     - 'gcr.io/[PROJECT_ID]/[IMAGE]'
  #     - '--region'
  #     - '[REGION]'
  #     - '--platform'
  #     - 'managed'
  #     - '--allow-unauthenticated'

tags:
  - build
  - deploy
