steps:
  - name: node:12.14.1
    entrypoint: npm
    args:
      - install
  # - name: gcr.io/cloud-builders/gcloud
  #   entrypoint: "bash"
  #   args:
  #     - "-c"
  #     - "gcloud secrets versions access latest --secret=api_url --format='get(payload.data)' | tr '_-' '/+' | base64 -d > api_url.txt"
  - name: node:12.14.1
    entrypoint: npm
    args:
      - "run"
      - "build:production"
      # - "-c"
      # - "API_URL=$(cat api_url.txt) npm run build:production"
    secretEnv:
      - "API_URL"
  - name: gcr.io/kaniko-project/executor:v0.23.0
    args:
      - --context=api/
      - --dockerfile=Dockerfile
      - --target=default
      - --destination=gcr.io/$PROJECT_ID/torii-api:$COMMIT_SHA
      - --build-arg=COMMIT_SHA=$COMMIT_SHA
      - --cache=true
      # Two weeks
      - --cache-ttl=336h
  - name: gcr.io/kaniko-project/executor:v0.23.0
    args:
      - --context=api/
      - --dockerfile=Dockerfile
      - --target=default
      - --destination=gcr.io/$PROJECT_ID/torii-api:latest
      - --cache=true
      - --cache-ttl=336h
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - torii-api
      - --image
      - gcr.io/$PROJECT_ID/torii-api:$COMMIT_SHA
      - --region
      - asia-northeast1
      - --platform
      - managed


secrets:
 - kmsKeyName: projects/torii-282017/locations/global/keyRings/main/cryptoKeys/app
   secretEnv:
     API_URL: "CiQA9WZzcMU1uVyv0gKgAMXkYtCIUMKrCiLRROHkeutxqiNLj/YSVQCxvTEqN0w8TjIoGw+xYERsjPhMvyGnr3zMZ1uUDODZK+z2NPifKAAU9BvjzD746cUJJbKLDxgcLFWY35LVrBdqe4si3QNyXVfopT+QL4tA6sc6/dw="

tags:
  - build
  - deploy
