steps:
  - name: node:14.16.1
    entrypoint: npm
    args:
      - install
  - name: node:14.16.1
    entrypoint: npm
    args:
      - "run"
      - "build:production"
    env:
      - "API_URL="
  - name: gcr.io/kaniko-project/executor:v0.24.0
    args:
      - --context=api/
      - --dockerfile=Dockerfile
      - --target=default
      - --destination=gcr.io/$PROJECT_ID/torii-api:$COMMIT_SHA
      - --build-arg=COMMIT_SHA=$COMMIT_SHA
      - --cache=true
      # Two weeks
      - --cache-ttl=336h
  - name: gcr.io/kaniko-project/executor:v0.24.0
    args:
      - --context=api/
      - --dockerfile=Dockerfile
      - --target=default
      - --destination=gcr.io/$PROJECT_ID/torii-api:latest
      - --cache=true
      - --cache-ttl=336h
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - torii-api
      - --image
      - gcr.io/$PROJECT_ID/torii-api:$COMMIT_SHA
      - --region
      - asia-northeast1
      - --platform
      - managed
  - name: gcr.io/$PROJECT_ID/firebase
    args:
      - deploy
      - --project
      - $PROJECT_ID
      - --only
      - hosting

tags:
  - build
  - deploy
