version: "3.7"
services:
  nginx:
    container_name: torii-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index_dev.html:/usr/share/nginx/html/index.html:ro
      - ./public:/usr/share/nginx/html/public:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  frontend:
    container_name: torii-frontend
    image: node:14.15.1-slim
    environment:
      - NODE_ENV=development
      - API_URL
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    image: torii-api-dev
    container_name: torii-api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/opt/torii_api
