version: "3"
services:
  nginx:
    container_name: torii-nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./index_dev.html:/usr/share/nginx/html/index.html:ro
      - ./images:/usr/share/nginx/html/images:ro
      - ./dist:/usr/share/nginx/html/dist:ro
      - ./torii.nginx.conf:/etc/nginx/conf.d/default.conf:ro
  webpack:
    container_name: torii-webpack
    image: node:10.14
    environment:
      - NODE_ENV=development
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
  api:
    container_name: torii-api
    image: python:3.6.3
    environment:
      - FLASK_APP=/app/app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app:ro
    working_dir: /app
    command: bash -c "pip install -r requirements-dev.txt && flask run --host=0.0.0.0"
