version: "3.8"
services:
  frontend:
    container_name: torii-frontend
    image: node:16.9.1-slim
    environment:
      - NODE_ENV=development
      - API_URL=http://0.0.0.0:5000
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "npm install && npm start"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    image: torii-api-dev
    container_name: torii-api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/opt/torii_api
