version: "3.7"
services:
  terraform:
    image: hashicorp/terraform:0.13.5
    container_name: torii-terraform
    environment:
      - GOOGLE_CREDENTIALS=/opt/service_account_key.json
    volumes:
      - .:/opt/
    working_dir: /opt/
