version: "3.8"
services:
  terraform:
    image: hashicorp/terraform:1.0.7
    container_name: torii-terraform
    environment:
      - GOOGLE_CREDENTIALS=/opt/service_account_key.json
    volumes:
      - .:/opt/
    working_dir: /opt/
