pip:
  restore_cache: &pip_restore_cache
    keys:
      - pip-v1-{{ .Branch }}-{{ checksum "api/requirements-dev.txt" }}-{{ checksum "api/requirements.txt" }}
      - pip-v1-{{ .Branch }}-
      - pip-v1-

  install:  &pip_install
    name: Install pip packages
    command: |
      python3 -m venv ~/venv
      . ~/venv/bin/activate
      pip install -r api/requirements-dev.txt

  save_cache: &pip_save_cache
    key: pip-v1-{{ .Branch }}-{{ checksum "api/requirements-dev.txt" }}-{{ checksum "api/requirements.txt" }}
    paths:
      - ~/venv
npm:
  restore_cache: &npm_restore_cache
    keys:
      - npm-v2-{{ .Branch }}-{{ checksum "package.json" }}
      - npm-v2-{{ .Branch }}-
      - npm-v2-

  install: &npm_install
    name: Install npm modules
    command: npm install

  save_cache: &npm_save_cache
    key: npm-v2-{{ .Branch }}-{{ checksum "package.json" }}
    paths:
      - ./node_modules


version: 2.1
orbs:
  terraform: circleci/terraform@1.2.0
executors:
  python:
    docker:
      - image: circleci/python:3.9.1
    working_directory: ~/torii
  nodejs:
    docker:
      - image: circleci/node:14.15.5
jobs:
  python-test:
    executor: python
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run tests
          command: |
            . ~/venv/bin/activate
            cd ./api
            ./../.circleci/nosetests.sh tests
      - store_test_results:
          path: api/dist

  flake8:
    executor: python
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run flake8
          command: |
            . ~/venv/bin/activate
            cd api/
            flake8 .

  isort:
    executor: python
    steps:
      - checkout
      - restore_cache:
          <<: *pip_restore_cache
      - run:
          <<: *pip_install
      - save_cache:
          <<: *pip_save_cache
      - run:
          name: Run isort check
          command: |
            . ~/venv/bin/activate
            cd api/
            isort --check --diff .

  eslint:
    executor: nodejs
    steps:
      - checkout
      - restore_cache:
          <<: *npm_restore_cache
      - run:
          <<: *npm_install
      - save_cache:
          <<: *npm_save_cache
      - run:
          name: Run eslint check
          command: npm run lint

workflows:
  version: 2
  test:
    jobs:
      - python-test
      - flake8
      - isort
      - eslint
      - terraform/fmt:
          checkout: true
          path: terraform/
      - terraform/validate:
          checkout: true
          backend: false
          path: terraform/
